import { describe, it, expect } from 'vitest';

import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

// @ts-expect-error: pure-JS Node script with no type declarations.
import {
  generateSitemap,
  buildSitemapXml,
  buildCaseStudyRoutes,
  withLocalePrefix,
  extractSlugs,
  extractVerticalSlugs,
  extractCaseStudySlugsFromPayload,
  extractCaseStudyEntriesFromPayload,
  loadCaseStudySlugs,
  loadCaseStudyEntries,
  resolveCaseStudySource,
  SUPPORTED_LOCALES,
  DEFAULT_LOCALE,
} from '../../scripts/generate-sitemap.mjs';

/**
 * Guards on the sitemap generator. The sitemap is checked into
 * `client-app/public/sitemap.xml` and regenerated by the `prebuild` hook in
 * `client-app/package.json`, so a regression in the generator would silently
 * ship a broken sitemap to production.
 */

describe('generate-sitemap script', () => {
  it('mirrors the i18n locale list from client-app/src/lib/i18n.ts', () => {
    expect(SUPPORTED_LOCALES).toEqual(['en', 'es', 'pt-BR', 'fr', 'de']);
    expect(DEFAULT_LOCALE).toBe('en');
  });

  it('withLocalePrefix matches the runtime helper', () => {
    expect(withLocalePrefix('en', '/pricing')).toBe('/pricing');
    expect(withLocalePrefix('en', '/')).toBe('/');
    expect(withLocalePrefix('pt-BR', '/pricing')).toBe('/pt-BR/pricing');
    expect(withLocalePrefix('pt-BR', '/')).toBe('/pt-BR');
    expect(withLocalePrefix('fr', '/docs/quickstart')).toBe('/fr/docs/quickstart');
  });

  describe('extractSlugs', () => {
    it('returns every slug literal in the source', () => {
      const src = "items: [\n  { slug: 'one' },\n  { slug: 'two-words' },\n]";
      expect(extractSlugs(src)).toEqual(['one', 'two-words']);
    });

    it('skips lines before startMarker (used to ignore docCategories)', () => {
      const src = `
        const cats = [
          { slug: 'category-one' },
        ];
        export const docArticles = [
          { slug: 'article-one' },
          { slug: 'article-two' },
        ];
      `;
      expect(extractSlugs(src, { startMarker: 'docArticles' })).toEqual([
        'article-one',
        'article-two',
      ]);
    });

    it('deduplicates repeats', () => {
      const src = "{ slug: 'foo' }, { slug: 'foo' }";
      expect(extractSlugs(src)).toEqual(['foo']);
    });
  });

  describe('extractVerticalSlugs', () => {
    it('returns the keys of the verticals Record', () => {
      // Synthetic minimal mirror of VerticalLanding.tsx so we don't depend
      // on the real file's exact vertical list (which evolves).
      const src = `
        const verticals: Record<string, VerticalConfig> = {
          healthcare: {
            slug: 'healthcare',
            heroImage: '/x.jpg',
            colorLight: 'bg-blue-50',
          },
          'real-estate': {
            slug: 'real-estate',
            heroImage: '/y.jpg',
          },
          legal: {
            slug: 'legal',
          },
        };
      `;
      expect(extractVerticalSlugs(src)).toEqual(['healthcare', 'real-estate', 'legal']);
    });

    it('does not pick up nested object keys (heroOverlayAccent, demoAgent, ...)', () => {
      const src = `
        const verticals: Record<string, VerticalConfig> = {
          healthcare: {
            slug: 'healthcare',
            nested: {
              deeper: {
                value: 'noise',
              },
            },
          },
          dental: {
            slug: 'dental',
          },
        };
      `;
      expect(extractVerticalSlugs(src)).toEqual(['healthcare', 'dental']);
    });

    it('throws when the verticals declaration is missing', () => {
      expect(() => extractVerticalSlugs('// no verticals here')).toThrow(
        /verticals map not found/,
      );
    });
  });

  describe('buildSitemapXml', () => {
    const fixedLastmod = '2026-04-29';

    it('emits a urlset with the xhtml namespace declared', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/pricing', changefreq: 'weekly', priority: '0.8' }],
        lastmod: fixedLastmod,
      });
      expect(xml).toContain('<?xml version="1.0" encoding="UTF-8"?>');
      expect(xml).toContain(
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
      );
      expect(xml.trim().endsWith('</urlset>')).toBe(true);
    });

    it('emits one <url> per (path × locale) pair', () => {
      const xml = buildSitemapXml({
        routes: [
          { path: '/pricing', changefreq: 'weekly', priority: '0.8' },
          { path: '/docs', changefreq: 'weekly', priority: '0.8' },
        ],
        lastmod: fixedLastmod,
      });
      const urlCount = (xml.match(/<url>/g) || []).length;
      expect(urlCount).toBe(2 * SUPPORTED_LOCALES.length);
    });

    it('every <url> entry includes the FULL set of hreflang siblings + x-default', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/pricing', changefreq: 'weekly', priority: '0.8' }],
        lastmod: fixedLastmod,
        baseUrl: 'https://qvo.ai',
      });
      // Each of the 5 locale variants of /pricing repeats the same 5
      // hreflang siblings + 1 x-default.
      const expectedAlternatesPerUrl = SUPPORTED_LOCALES.length + 1;
      const totalAlternates = (xml.match(/<xhtml:link\b/g) || []).length;
      expect(totalAlternates).toBe(SUPPORTED_LOCALES.length * expectedAlternatesPerUrl);

      // Spot-check the alternates point at the right localized URLs.
      expect(xml).toContain('hreflang="en" href="https://qvo.ai/pricing"');
      expect(xml).toContain('hreflang="es" href="https://qvo.ai/es/pricing"');
      expect(xml).toContain('hreflang="pt-BR" href="https://qvo.ai/pt-BR/pricing"');
      expect(xml).toContain('hreflang="fr" href="https://qvo.ai/fr/pricing"');
      expect(xml).toContain('hreflang="de" href="https://qvo.ai/de/pricing"');
      expect(xml).toContain('hreflang="x-default" href="https://qvo.ai/pricing"');
    });

    it('default locale (en) is served from un-prefixed URLs, others are prefixed', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/pricing', changefreq: 'weekly', priority: '0.8' }],
        lastmod: fixedLastmod,
        baseUrl: 'https://qvo.ai',
      });
      expect(xml).toContain('<loc>https://qvo.ai/pricing</loc>');
      expect(xml).toContain('<loc>https://qvo.ai/es/pricing</loc>');
      expect(xml).toContain('<loc>https://qvo.ai/pt-BR/pricing</loc>');
      // No /en/ prefix should ever appear.
      expect(xml).not.toMatch(/<loc>https:\/\/qvo\.ai\/en\b/);
    });

    it('escapes XML-unsafe characters in URLs (defense in depth)', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/q?x=1&y=2', changefreq: 'weekly', priority: '0.5' }],
        lastmod: fixedLastmod,
        baseUrl: 'https://qvo.ai',
      });
      expect(xml).toContain('<loc>https://qvo.ai/q?x=1&amp;y=2</loc>');
      // The raw `&y=2` (unescaped) would produce a `?x=1&y=2` substring; the
      // escaper turns that into `&amp;`, so the unescaped form must not appear.
      expect(xml).not.toContain('?x=1&y=2');
    });
  });

  describe('extractCaseStudySlugsFromPayload', () => {
    it('returns publicSlug values from a list of case studies', () => {
      const payload = [
        { id: '1', publicSlug: 'acme-co' },
        { id: '2', publicSlug: 'globex-clinic' },
      ];
      expect(extractCaseStudySlugsFromPayload(payload)).toEqual([
        'acme-co',
        'globex-clinic',
      ]);
    });

    it('also accepts public_slug (snake_case) for raw DB snapshots', () => {
      const payload = [{ id: '1', public_slug: 'snake-cased' }];
      expect(extractCaseStudySlugsFromPayload(payload)).toEqual(['snake-cased']);
    });

    it('drops null / missing slugs (unpublished studies)', () => {
      const payload = [
        { id: '1', publicSlug: null },
        { id: '2' },
        { id: '3', publicSlug: 'real-slug' },
      ];
      expect(extractCaseStudySlugsFromPayload(payload)).toEqual(['real-slug']);
    });

    it('drops slugs that would produce invalid URL segments', () => {
      const payload = [
        { id: '1', publicSlug: 'Has Spaces' },
        { id: '2', publicSlug: '-leading-hyphen' },
        { id: '3', publicSlug: 'CapsAreBad' },
        { id: '4', publicSlug: 'good-slug' },
      ];
      expect(extractCaseStudySlugsFromPayload(payload)).toEqual(['good-slug']);
    });

    it('deduplicates repeated slugs', () => {
      const payload = [
        { id: '1', publicSlug: 'foo' },
        { id: '2', publicSlug: 'foo' },
      ];
      expect(extractCaseStudySlugsFromPayload(payload)).toEqual(['foo']);
    });

    it('returns an empty array for non-array input (defensive)', () => {
      expect(extractCaseStudySlugsFromPayload(null)).toEqual([]);
      expect(extractCaseStudySlugsFromPayload({})).toEqual([]);
      expect(extractCaseStudySlugsFromPayload('oops')).toEqual([]);
    });
  });

  describe('buildCaseStudyRoutes', () => {
    it('produces /case-studies/<slug> route entries with monthly cadence', () => {
      expect(buildCaseStudyRoutes(['acme-co', 'globex'])).toEqual([
        { path: '/case-studies/acme-co', changefreq: 'monthly', priority: '0.6' },
        { path: '/case-studies/globex', changefreq: 'monthly', priority: '0.6' },
      ]);
    });

    it('silently skips invalid slugs', () => {
      expect(buildCaseStudyRoutes(['ok', 'BAD!', '', null, undefined, 'also-ok'])).toEqual([
        { path: '/case-studies/ok', changefreq: 'monthly', priority: '0.6' },
        { path: '/case-studies/also-ok', changefreq: 'monthly', priority: '0.6' },
      ]);
    });
  });

  describe('loadCaseStudySlugs', () => {
    const silentLogger = { warn: () => {} };

    it('fetches from the URL and returns valid slugs', async () => {
      const fetchImpl = async (url: string) => {
        expect(url).toBe('https://qvo.ai/api/public/case-studies');
        return {
          ok: true,
          status: 200,
          json: async () => [
            { id: '1', publicSlug: 'acme-co' },
            { id: '2', publicSlug: null },
            { id: '3', publicSlug: 'globex' },
          ],
        };
      };
      const slugs = await loadCaseStudySlugs({
        url: 'https://qvo.ai/api/public/case-studies',
        fetchImpl,
        logger: silentLogger,
      });
      expect(slugs).toEqual(['acme-co', 'globex']);
    });

    it('returns [] (does NOT throw) when the API returns a non-2xx status', async () => {
      const fetchImpl = async () => ({ ok: false, status: 503, json: async () => ({}) });
      const slugs = await loadCaseStudySlugs({
        url: 'https://qvo.ai/api/public/case-studies',
        fetchImpl,
        logger: silentLogger,
      });
      expect(slugs).toEqual([]);
    });

    it('returns [] (does NOT throw) when fetch itself rejects (network down)', async () => {
      const fetchImpl = async () => {
        throw new Error('ECONNREFUSED');
      };
      const slugs = await loadCaseStudySlugs({
        url: 'https://qvo.ai/api/public/case-studies',
        fetchImpl,
        logger: silentLogger,
      });
      expect(slugs).toEqual([]);
    });

    it('returns [] (does NOT throw) when the body is not valid JSON', async () => {
      const fetchImpl = async () => ({
        ok: true,
        status: 200,
        json: async () => {
          throw new SyntaxError('Unexpected token <');
        },
      });
      const slugs = await loadCaseStudySlugs({
        url: 'https://qvo.ai/api/public/case-studies',
        fetchImpl,
        logger: silentLogger,
      });
      expect(slugs).toEqual([]);
    });

    it('reads from a local snapshot file when no URL is provided', async () => {
      const dir = mkdtempSync(path.join(tmpdir(), 'sitemap-cs-'));
      const file = path.join(dir, 'case-studies.json');
      writeFileSync(
        file,
        JSON.stringify([
          { id: '1', publicSlug: 'from-file' },
          { id: '2', publicSlug: 'and-another' },
        ]),
      );
      try {
        const slugs = await loadCaseStudySlugs({ file, logger: silentLogger });
        expect(slugs).toEqual(['from-file', 'and-another']);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });

    it('returns [] when the snapshot file is missing (does NOT throw)', async () => {
      const slugs = await loadCaseStudySlugs({
        file: '/tmp/definitely-not-here-' + Math.random().toString(36).slice(2) + '.json',
        logger: silentLogger,
      });
      expect(slugs).toEqual([]);
    });

    it('returns [] when neither url nor file is provided (default no-op)', async () => {
      const slugs = await loadCaseStudySlugs({ logger: silentLogger });
      expect(slugs).toEqual([]);
    });
  });

  describe('resolveCaseStudySource', () => {
    it('defaults to ${baseUrl}/api/public/case-studies when no env vars are set', () => {
      const source = resolveCaseStudySource({ env: {}, baseUrl: 'https://qvo.ai' });
      expect(source).toEqual({ url: 'https://qvo.ai/api/public/case-studies' });
    });

    it('honors SITEMAP_CASE_STUDIES_URL as an override', () => {
      const source = resolveCaseStudySource({
        env: { SITEMAP_CASE_STUDIES_URL: 'https://staging.example.com/api/public/case-studies' },
        baseUrl: 'https://qvo.ai',
      });
      expect(source).toEqual({
        url: 'https://staging.example.com/api/public/case-studies',
      });
    });

    it('disables case-study URLs when SITEMAP_CASE_STUDIES_URL is empty', () => {
      const source = resolveCaseStudySource({
        env: { SITEMAP_CASE_STUDIES_URL: '' },
        baseUrl: 'https://qvo.ai',
      });
      expect(source).toEqual({});
    });

    it('disables case-study URLs when SITEMAP_CASE_STUDIES_URL is "none"', () => {
      const source = resolveCaseStudySource({
        env: { SITEMAP_CASE_STUDIES_URL: 'none' },
        baseUrl: 'https://qvo.ai',
      });
      expect(source).toEqual({});
    });

    it('prefers the SITEMAP_CASE_STUDIES_FILE snapshot over any URL', () => {
      const source = resolveCaseStudySource({
        env: {
          SITEMAP_CASE_STUDIES_FILE: '/snapshots/case-studies.json',
          SITEMAP_CASE_STUDIES_URL: 'https://qvo.ai/api/public/case-studies',
        },
        baseUrl: 'https://qvo.ai',
      });
      expect(source).toEqual({ file: '/snapshots/case-studies.json' });
    });
  });

  describe('CLI default flow (resolve + load)', () => {
    const silentLogger = { warn: () => {} };

    it('default CLI behavior fetches from the API and surfaces real slugs', async () => {
      const calls: string[] = [];
      const fetchImpl = async (url: string) => {
        calls.push(url);
        return {
          ok: true,
          status: 200,
          json: async () => [
            { id: '1', publicSlug: 'real-customer-one' },
            { id: '2', publicSlug: 'real-customer-two' },
          ],
        };
      };
      const source = resolveCaseStudySource({ env: {}, baseUrl: 'https://qvo.ai' });
      const slugs = await loadCaseStudySlugs({ ...source, fetchImpl, logger: silentLogger });
      expect(calls).toEqual(['https://qvo.ai/api/public/case-studies']);
      expect(slugs).toEqual(['real-customer-one', 'real-customer-two']);
    });

    it('default CLI behavior gracefully skips case-study URLs when the API is unreachable', async () => {
      const fetchImpl = async () => {
        throw new Error('ENOTFOUND qvo.ai');
      };
      const source = resolveCaseStudySource({ env: {}, baseUrl: 'https://qvo.ai' });
      const slugs = await loadCaseStudySlugs({ ...source, fetchImpl, logger: silentLogger });
      expect(slugs).toEqual([]);
      // And the rest of the sitemap still builds correctly with zero slugs:
      const xml = generateSitemap({ caseStudySlugs: slugs, lastmod: '2026-04-29' });
      expect(xml).toContain('<loc>https://qvo.ai/case-studies</loc>');
      expect(xml).not.toMatch(/<loc>https:\/\/qvo\.ai\/case-studies\/[a-z]/);
    });

    it('default CLI behavior gracefully skips case-study URLs when the API returns an error status', async () => {
      const fetchImpl = async () => ({ ok: false, status: 500, json: async () => ({}) });
      const source = resolveCaseStudySource({ env: {}, baseUrl: 'https://qvo.ai' });
      const slugs = await loadCaseStudySlugs({ ...source, fetchImpl, logger: silentLogger });
      expect(slugs).toEqual([]);
    });
  });

  describe('generateSitemap with caseStudySlugs', () => {
    it('emits /case-studies/<slug> URLs for every locale when slugs are provided', () => {
      const xml = generateSitemap({
        lastmod: '2026-04-29',
        caseStudySlugs: ['acme-co', 'globex-clinic'],
      });
      for (const slug of ['acme-co', 'globex-clinic']) {
        for (const locale of SUPPORTED_LOCALES) {
          const url = `https://qvo.ai${withLocalePrefix(locale, `/case-studies/${slug}`)}`;
          expect(xml, `missing <loc>${url}</loc>`).toContain(`<loc>${url}</loc>`);
        }
        // hreflang siblings + x-default are emitted per the same rules as
        // every other route — spot-check the x-default for one slug.
        expect(xml).toContain(
          `hreflang="x-default" href="https://qvo.ai/case-studies/${slug}"`,
        );
      }
    });

    it('does NOT emit any /case-studies/<slug> URLs when no slugs are provided', () => {
      const xml = generateSitemap({ lastmod: '2026-04-29' });
      // The index page /case-studies is in STATIC_ROUTES so it MUST appear,
      // but no individual story URLs should leak in.
      expect(xml).toContain('<loc>https://qvo.ai/case-studies</loc>');
      expect(xml).not.toMatch(/<loc>https:\/\/qvo\.ai\/case-studies\/[a-z]/);
    });

    it('skips invalid case-study slugs without failing the build', () => {
      const xml = generateSitemap({
        lastmod: '2026-04-29',
        caseStudySlugs: ['valid-one', 'BAD slug', '', 'valid-two'],
      });
      expect(xml).toContain('<loc>https://qvo.ai/case-studies/valid-one</loc>');
      expect(xml).toContain('<loc>https://qvo.ai/case-studies/valid-two</loc>');
      expect(xml).not.toContain('BAD slug');
    });

    it('preserves the underscore-bearing slug format produced by CaseStudyService.generateCaseStudy', () => {
      // Real publicSlug values look like `cs-<base36hash>-<milestone.type>-<value>`,
      // and milestone.type is snake_case (`call_volume`, `cost_savings`,
      // `time_in_service`). Regression test for #1184: an earlier validator
      // that excluded underscores silently dropped every real customer.
      const realisticSlugs = [
        'cs-1abc-call_volume-500',
        'cs-2def-cost_savings-40',
        'cs-3ghi-time_in_service-90',
      ];
      const apiPayload = realisticSlugs.map((slug, i) => ({ id: String(i), publicSlug: slug }));
      // Round-trip through the extractor (mirrors what loadCaseStudySlugs does)
      // so we prove the API → sitemap pipeline lets these through end-to-end.
      const extracted = extractCaseStudySlugsFromPayload(apiPayload);
      expect(extracted).toEqual(realisticSlugs);

      const xml = generateSitemap({ lastmod: '2026-04-29', caseStudySlugs: extracted });
      for (const slug of realisticSlugs) {
        for (const locale of SUPPORTED_LOCALES) {
          const url = `https://qvo.ai${withLocalePrefix(locale, `/case-studies/${slug}`)}`;
          expect(xml, `missing <loc>${url}</loc>`).toContain(`<loc>${url}</loc>`);
        }
        expect(xml).toContain(
          `hreflang="x-default" href="https://qvo.ai/case-studies/${slug}"`,
        );
      }
    });
  });

  describe('generateSitemap (real codebase)', () => {
    const xml = generateSitemap({ lastmod: '2026-04-29' });

    it('includes core public marketing routes for every locale', () => {
      const expectPathInEveryLocale = (p: string) => {
        for (const locale of SUPPORTED_LOCALES) {
          const url = `https://qvo.ai${withLocalePrefix(locale, p)}`;
          expect(xml, `missing <loc>${url}</loc>`).toContain(`<loc>${url}</loc>`);
        }
      };
      ['/', '/pricing', '/demo', '/contact', '/industries/healthcare', '/book-demo'].forEach(expectPathInEveryLocale);
    });

    it('does not publish deferred generic blog, docs, resource, or vertical routes', () => {
      const hidden = [
        '/docs/quickstart',
        '/blog/what-are-ai-voice-agents',
        '/resources/getting-started-with-qvo',
        '/industries/home-services',
      ];
      for (const p of hidden) {
        expect(xml).not.toContain(`<loc>https://qvo.ai${p}</loc>`);
      }
    });

    it('does not list authenticated/in-app routes (those are in robots Disallow)', () => {
      // Sanity: tenant + admin + ops surfaces should NEVER appear in the sitemap.
      const forbidden = ['/dashboard', '/agents', '/admin/', '/ops/', '/onboarding'];
      for (const p of forbidden) {
        expect(xml).not.toContain(`<loc>https://qvo.ai${p}`);
      }
    });
  });

  /**
   * Per-route `<lastmod>` plumbing — the whole point of task #1229. Case
   * studies have real `createdAt`/`updatedAt` timestamps in the
   * `/api/public/case-studies` payload, so they should be carried through to
   * the sitemap instead of being stamped with today's build date.
   */
  describe('per-route lastmod (case-study freshness)', () => {
    describe('extractCaseStudyEntriesFromPayload', () => {
      it('returns slug + normalized lastmod from updatedAt (preferred over createdAt)', () => {
        const payload = [
          {
            id: '1',
            publicSlug: 'acme-co',
            createdAt: '2026-01-10T10:00:00.000Z',
            updatedAt: '2026-04-22T14:30:00.000Z',
          },
        ];
        expect(extractCaseStudyEntriesFromPayload(payload)).toEqual([
          { slug: 'acme-co', lastmod: '2026-04-22' },
        ]);
      });

      it('falls back to createdAt when updatedAt is missing', () => {
        const payload = [
          { id: '1', publicSlug: 'just-created', createdAt: '2026-03-15T09:00:00.000Z' },
        ];
        expect(extractCaseStudyEntriesFromPayload(payload)).toEqual([
          { slug: 'just-created', lastmod: '2026-03-15' },
        ]);
      });

      it('accepts snake_case fields (raw DB row snapshots)', () => {
        const payload = [
          {
            id: '1',
            public_slug: 'snake-cased',
            created_at: '2026-02-01T00:00:00.000Z',
            updated_at: '2026-02-20T00:00:00.000Z',
          },
        ];
        expect(extractCaseStudyEntriesFromPayload(payload)).toEqual([
          { slug: 'snake-cased', lastmod: '2026-02-20' },
        ]);
      });

      it('omits lastmod entirely when no parseable timestamp is available', () => {
        const payload = [
          { id: '1', publicSlug: 'no-dates' },
          { id: '2', publicSlug: 'bad-dates', updatedAt: 'not-a-date', createdAt: '' },
        ];
        expect(extractCaseStudyEntriesFromPayload(payload)).toEqual([
          { slug: 'no-dates' },
          { slug: 'bad-dates' },
        ]);
      });

      it('still drops invalid slugs / non-arrays the same way the slug-only extractor does', () => {
        expect(extractCaseStudyEntriesFromPayload(null)).toEqual([]);
        expect(
          extractCaseStudyEntriesFromPayload([
            { id: '1', publicSlug: 'Has Spaces', updatedAt: '2026-04-01' },
            { id: '2', publicSlug: 'good', updatedAt: '2026-04-01T00:00:00Z' },
          ]),
        ).toEqual([{ slug: 'good', lastmod: '2026-04-01' }]);
      });

      it('deduplicates repeated slugs, keeping the first entry seen', () => {
        const payload = [
          { id: '1', publicSlug: 'foo', updatedAt: '2026-04-01T00:00:00Z' },
          { id: '2', publicSlug: 'foo', updatedAt: '2026-05-01T00:00:00Z' },
        ];
        expect(extractCaseStudyEntriesFromPayload(payload)).toEqual([
          { slug: 'foo', lastmod: '2026-04-01' },
        ]);
      });

      it('extractCaseStudySlugsFromPayload still returns bare strings (back-compat)', () => {
        const payload = [
          { id: '1', publicSlug: 'foo', updatedAt: '2026-04-01T00:00:00Z' },
          { id: '2', publicSlug: 'bar', createdAt: '2026-03-01T00:00:00Z' },
        ];
        expect(extractCaseStudySlugsFromPayload(payload)).toEqual(['foo', 'bar']);
      });
    });

    describe('loadCaseStudyEntries', () => {
      const silentLogger = { warn: () => {} };

      it('fetches entries (slug + lastmod) from the API', async () => {
        const fetchImpl = async () => ({
          ok: true,
          status: 200,
          json: async () => [
            {
              id: '1',
              publicSlug: 'acme-co',
              createdAt: '2026-01-01T00:00:00Z',
              updatedAt: '2026-04-15T00:00:00Z',
            },
            { id: '2', publicSlug: 'globex', createdAt: '2026-02-10T00:00:00Z' },
          ],
        });
        const entries = await loadCaseStudyEntries({
          url: 'https://qvo.ai/api/public/case-studies',
          fetchImpl,
          logger: silentLogger,
        });
        expect(entries).toEqual([
          { slug: 'acme-co', lastmod: '2026-04-15' },
          { slug: 'globex', lastmod: '2026-02-10' },
        ]);
      });

      it('returns [] (does NOT throw) when the API is unreachable', async () => {
        const fetchImpl = async () => {
          throw new Error('ENOTFOUND');
        };
        const entries = await loadCaseStudyEntries({
          url: 'https://qvo.ai/api/public/case-studies',
          fetchImpl,
          logger: silentLogger,
        });
        expect(entries).toEqual([]);
      });

      it('reads from a snapshot file when no URL is provided', async () => {
        const dir = mkdtempSync(path.join(tmpdir(), 'sitemap-cs-entries-'));
        const file = path.join(dir, 'case-studies.json');
        writeFileSync(
          file,
          JSON.stringify([
            { id: '1', publicSlug: 'from-file', updatedAt: '2026-03-30T00:00:00Z' },
          ]),
        );
        try {
          const entries = await loadCaseStudyEntries({ file, logger: silentLogger });
          expect(entries).toEqual([{ slug: 'from-file', lastmod: '2026-03-30' }]);
        } finally {
          rmSync(dir, { recursive: true, force: true });
        }
      });

      it('loadCaseStudySlugs still returns bare strings derived from the same payload', async () => {
        const fetchImpl = async () => ({
          ok: true,
          status: 200,
          json: async () => [
            { id: '1', publicSlug: 'one', updatedAt: '2026-04-01T00:00:00Z' },
            { id: '2', publicSlug: 'two', createdAt: '2026-03-01T00:00:00Z' },
          ],
        });
        const slugs = await loadCaseStudySlugs({
          url: 'https://qvo.ai/api/public/case-studies',
          fetchImpl,
          logger: silentLogger,
        });
        expect(slugs).toEqual(['one', 'two']);
      });
    });

    describe('buildCaseStudyRoutes accepts entries with lastmod', () => {
      it('attaches lastmod to the route when provided', () => {
        expect(
          buildCaseStudyRoutes([
            { slug: 'acme-co', lastmod: '2026-04-15' },
            { slug: 'globex' },
          ]),
        ).toEqual([
          {
            path: '/case-studies/acme-co',
            changefreq: 'monthly',
            priority: '0.6',
            lastmod: '2026-04-15',
          },
          { path: '/case-studies/globex', changefreq: 'monthly', priority: '0.6' },
        ]);
      });

      it('still accepts bare slug strings for back-compat', () => {
        expect(buildCaseStudyRoutes(['acme-co'])).toEqual([
          { path: '/case-studies/acme-co', changefreq: 'monthly', priority: '0.6' },
        ]);
      });
    });

    describe('buildSitemapXml emits per-route <lastmod>', () => {
      it('uses route.lastmod when present, falling back to the build-time default otherwise', () => {
        const xml = buildSitemapXml({
          routes: [
            // Static route — no per-route override → today's date.
            { path: '/pricing', changefreq: 'weekly', priority: '0.8' },
            // Case-study route — carries its own real lastmod.
            {
              path: '/case-studies/acme-co',
              changefreq: 'monthly',
              priority: '0.6',
              lastmod: '2026-04-15',
            },
          ],
          lastmod: '2026-04-29',
          baseUrl: 'https://qvo.ai',
        });

        // The static route uses the build default for every locale variant.
        const pricingDefaultLastmod = (xml.match(/<lastmod>2026-04-29<\/lastmod>/g) || []).length;
        expect(pricingDefaultLastmod).toBe(SUPPORTED_LOCALES.length);

        // The case study uses its own lastmod for every locale variant.
        const acmeRealLastmod = (xml.match(/<lastmod>2026-04-15<\/lastmod>/g) || []).length;
        expect(acmeRealLastmod).toBe(SUPPORTED_LOCALES.length);
      });
    });

    describe('generateSitemap with caseStudyEntries', () => {
      it('emits real per-URL <lastmod> values for case-study routes', () => {
        const xml = generateSitemap({
          lastmod: '2026-04-29',
          caseStudyEntries: [
            { slug: 'acme-co', lastmod: '2026-04-15' },
            { slug: 'globex', lastmod: '2026-02-10' },
            // No lastmod available — should fall back to the build-time default.
            { slug: 'no-date' },
          ],
        });

        // Each case study with a real lastmod appears once per locale.
        expect((xml.match(/<lastmod>2026-04-15<\/lastmod>/g) || []).length).toBe(
          SUPPORTED_LOCALES.length,
        );
        expect((xml.match(/<lastmod>2026-02-10<\/lastmod>/g) || []).length).toBe(
          SUPPORTED_LOCALES.length,
        );

        // Sanity: the actual case-study URLs are present too.
        for (const slug of ['acme-co', 'globex', 'no-date']) {
          for (const locale of SUPPORTED_LOCALES) {
            const url = `https://qvo.ai${withLocalePrefix(locale, `/case-studies/${slug}`)}`;
            expect(xml, `missing <loc>${url}</loc>`).toContain(`<loc>${url}</loc>`);
          }
        }
      });

      it('caseStudyEntries takes precedence over the legacy caseStudySlugs param', () => {
        const xml = generateSitemap({
          lastmod: '2026-04-29',
          caseStudySlugs: ['ignored-when-entries-provided'],
          caseStudyEntries: [{ slug: 'real-entry', lastmod: '2026-04-20' }],
        });
        expect(xml).toContain('<loc>https://qvo.ai/case-studies/real-entry</loc>');
        expect(xml).not.toContain('ignored-when-entries-provided');
        expect((xml.match(/<lastmod>2026-04-20<\/lastmod>/g) || []).length).toBe(
          SUPPORTED_LOCALES.length,
        );
      });
    });
  });
});
