import { describe, it, expect } from 'vitest';

// @ts-expect-error: pure-JS Node script with no type declarations.
import {
  generateSitemap,
  buildSitemapXml,
  withLocalePrefix,
  extractSlugs,
  extractVerticalSlugs,
  SUPPORTED_LOCALES,
  DEFAULT_LOCALE,
} from '../../scripts/generate-sitemap.mjs';

/**
 * Guards on the sitemap generator. The sitemap is checked into
 * `client-app/public/sitemap.xml` and regenerated by the `prebuild` hook in
 * `client-app/package.json`, so a regression in the generator would silently
 * ship a broken sitemap to production.
 */

describe('generate-sitemap script', () => {
  it('mirrors the i18n locale list from client-app/src/lib/i18n.ts', () => {
    expect(SUPPORTED_LOCALES).toEqual(['en', 'es', 'pt-BR', 'fr', 'de']);
    expect(DEFAULT_LOCALE).toBe('en');
  });

  it('withLocalePrefix matches the runtime helper', () => {
    expect(withLocalePrefix('en', '/pricing')).toBe('/pricing');
    expect(withLocalePrefix('en', '/')).toBe('/');
    expect(withLocalePrefix('pt-BR', '/pricing')).toBe('/pt-BR/pricing');
    expect(withLocalePrefix('pt-BR', '/')).toBe('/pt-BR');
    expect(withLocalePrefix('fr', '/docs/quickstart')).toBe('/fr/docs/quickstart');
  });

  describe('extractSlugs', () => {
    it('returns every slug literal in the source', () => {
      const src = "items: [\n  { slug: 'one' },\n  { slug: 'two-words' },\n]";
      expect(extractSlugs(src)).toEqual(['one', 'two-words']);
    });

    it('skips lines before startMarker (used to ignore docCategories)', () => {
      const src = `
        const cats = [
          { slug: 'category-one' },
        ];
        export const docArticles = [
          { slug: 'article-one' },
          { slug: 'article-two' },
        ];
      `;
      expect(extractSlugs(src, { startMarker: 'docArticles' })).toEqual([
        'article-one',
        'article-two',
      ]);
    });

    it('deduplicates repeats', () => {
      const src = "{ slug: 'foo' }, { slug: 'foo' }";
      expect(extractSlugs(src)).toEqual(['foo']);
    });
  });

  describe('extractVerticalSlugs', () => {
    it('returns the keys of the verticals Record', () => {
      // Synthetic minimal mirror of VerticalLanding.tsx so we don't depend
      // on the real file's exact vertical list (which evolves).
      const src = `
        const verticals: Record<string, VerticalConfig> = {
          healthcare: {
            slug: 'healthcare',
            heroImage: '/x.jpg',
            colorLight: 'bg-blue-50',
          },
          'real-estate': {
            slug: 'real-estate',
            heroImage: '/y.jpg',
          },
          legal: {
            slug: 'legal',
          },
        };
      `;
      expect(extractVerticalSlugs(src)).toEqual(['healthcare', 'real-estate', 'legal']);
    });

    it('does not pick up nested object keys (heroOverlayAccent, demoAgent, ...)', () => {
      const src = `
        const verticals: Record<string, VerticalConfig> = {
          healthcare: {
            slug: 'healthcare',
            nested: {
              deeper: {
                value: 'noise',
              },
            },
          },
          dental: {
            slug: 'dental',
          },
        };
      `;
      expect(extractVerticalSlugs(src)).toEqual(['healthcare', 'dental']);
    });

    it('throws when the verticals declaration is missing', () => {
      expect(() => extractVerticalSlugs('// no verticals here')).toThrow(
        /verticals map not found/,
      );
    });
  });

  describe('buildSitemapXml', () => {
    const fixedLastmod = '2026-04-29';

    it('emits a urlset with the xhtml namespace declared', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/pricing', changefreq: 'weekly', priority: '0.8' }],
        lastmod: fixedLastmod,
      });
      expect(xml).toContain('<?xml version="1.0" encoding="UTF-8"?>');
      expect(xml).toContain(
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
      );
      expect(xml.trim().endsWith('</urlset>')).toBe(true);
    });

    it('emits one <url> per (path × locale) pair', () => {
      const xml = buildSitemapXml({
        routes: [
          { path: '/pricing', changefreq: 'weekly', priority: '0.8' },
          { path: '/docs', changefreq: 'weekly', priority: '0.8' },
        ],
        lastmod: fixedLastmod,
      });
      const urlCount = (xml.match(/<url>/g) || []).length;
      expect(urlCount).toBe(2 * SUPPORTED_LOCALES.length);
    });

    it('every <url> entry includes the FULL set of hreflang siblings + x-default', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/pricing', changefreq: 'weekly', priority: '0.8' }],
        lastmod: fixedLastmod,
        baseUrl: 'https://qvo.ai',
      });
      // Each of the 5 locale variants of /pricing repeats the same 5
      // hreflang siblings + 1 x-default.
      const expectedAlternatesPerUrl = SUPPORTED_LOCALES.length + 1;
      const totalAlternates = (xml.match(/<xhtml:link\b/g) || []).length;
      expect(totalAlternates).toBe(SUPPORTED_LOCALES.length * expectedAlternatesPerUrl);

      // Spot-check the alternates point at the right localized URLs.
      expect(xml).toContain('hreflang="en" href="https://qvo.ai/pricing"');
      expect(xml).toContain('hreflang="es" href="https://qvo.ai/es/pricing"');
      expect(xml).toContain('hreflang="pt-BR" href="https://qvo.ai/pt-BR/pricing"');
      expect(xml).toContain('hreflang="fr" href="https://qvo.ai/fr/pricing"');
      expect(xml).toContain('hreflang="de" href="https://qvo.ai/de/pricing"');
      expect(xml).toContain('hreflang="x-default" href="https://qvo.ai/pricing"');
    });

    it('default locale (en) is served from un-prefixed URLs, others are prefixed', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/pricing', changefreq: 'weekly', priority: '0.8' }],
        lastmod: fixedLastmod,
        baseUrl: 'https://qvo.ai',
      });
      expect(xml).toContain('<loc>https://qvo.ai/pricing</loc>');
      expect(xml).toContain('<loc>https://qvo.ai/es/pricing</loc>');
      expect(xml).toContain('<loc>https://qvo.ai/pt-BR/pricing</loc>');
      // No /en/ prefix should ever appear.
      expect(xml).not.toMatch(/<loc>https:\/\/qvo\.ai\/en\b/);
    });

    it('escapes XML-unsafe characters in URLs (defense in depth)', () => {
      const xml = buildSitemapXml({
        routes: [{ path: '/q?x=1&y=2', changefreq: 'weekly', priority: '0.5' }],
        lastmod: fixedLastmod,
        baseUrl: 'https://qvo.ai',
      });
      expect(xml).toContain('<loc>https://qvo.ai/q?x=1&amp;y=2</loc>');
      // The raw `&y=2` (unescaped) would produce a `?x=1&y=2` substring; the
      // escaper turns that into `&amp;`, so the unescaped form must not appear.
      expect(xml).not.toContain('?x=1&y=2');
    });
  });

  describe('generateSitemap (real codebase)', () => {
    const xml = generateSitemap({ lastmod: '2026-04-29' });

    it('includes core public marketing routes for every locale', () => {
      const expectPathInEveryLocale = (p: string) => {
        for (const locale of SUPPORTED_LOCALES) {
          const url = `https://qvo.ai${withLocalePrefix(locale, p)}`;
          expect(xml, `missing <loc>${url}</loc>`).toContain(`<loc>${url}</loc>`);
        }
      };
      ['/', '/pricing', '/features', '/docs', '/blog', '/book-demo'].forEach(expectPathInEveryLocale);
    });

    it('includes dynamic doc/blog/guide/vertical slugs per locale', () => {
      // These are stable slugs from the data files and the verticals map.
      // If any of them ever genuinely disappears, update this test alongside.
      const samples = [
        '/docs/quickstart',
        '/blog/what-are-ai-voice-agents',
        '/resources/getting-started-with-qvo',
        '/industries/healthcare',
        '/industries/dental',
        '/industries/home-services',
      ];
      for (const p of samples) {
        for (const locale of SUPPORTED_LOCALES) {
          const url = `https://qvo.ai${withLocalePrefix(locale, p)}`;
          expect(xml, `missing <loc>${url}</loc>`).toContain(`<loc>${url}</loc>`);
        }
      }
    });

    it('does not list authenticated/in-app routes (those are in robots Disallow)', () => {
      // Sanity: tenant + admin + ops surfaces should NEVER appear in the sitemap.
      const forbidden = ['/dashboard', '/agents', '/admin/', '/ops/', '/onboarding'];
      for (const p of forbidden) {
        expect(xml).not.toContain(`<loc>https://qvo.ai${p}`);
      }
    });
  });
});
